######
# Build with:
# docker buildx build -t rlkvch/caddy:2.9.0-beta.3 -t rlkvch/caddy:v2.9-latest --platform linux/amd64,linux/arm64 -f Dockerfile.caddy-2.9.0-beta.3 --push .
######

FROM golang:1.22.3 AS builder
ARG CADDY_VERSION=2.9.0-beta.3

RUN go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

RUN xcaddy build v${CADDY_VERSION} \
    --with github.com/caddy-dns/godaddy \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/caddyserver/transform-encoder \
    --with github.com/sagikazarmark/caddy-fs-s3 \
    --with github.com/caddyserver/certmagic=github.com/caddyserver/certmagic@master \
    --output /usr/bin/caddy

FROM caddy:latest

LABEL maintainer="Ilya Arlukevich <arlukevich@proton.me>"

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

WORKDIR /etc/caddy

EXPOSE 80 443

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
