name: Build and push Caddy Docker Images

on:
  push:
    branches:
      - main
#   paths:
#     - 'caddy/**'
#     - 'caddy/**'

jobs:
  build_and_push_v2-7-6:
    if: contains(github.event.head_commit.message, 'build/caddy:2.7.6') || contains(github.event.head_commit.message, 'build/all')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      run: cd ./caddy && docker buildx build -t rlkvch/caddy:2.7.6 -t rlkvch/caddy:v2.7-latest --platform linux/amd64,linux/arm,linux/arm64,linux/ppc64le -f Dockerfile.caddy-2.7.6 --push .

  build_and_push_v2-8-0-beta-2:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'build/caddy:2.8.0-beta.2') || contains(github.event.head_commit.message, 'build/all')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      run: cd ./caddy && docker buildx build -t rlkvch/caddy:v2.8.0-beta.2 -t rlkvch/caddy:v2.8-latest --platform linux/amd64,linux/arm,linux/arm64,linux/arm,linux/ppc64le -f Dockerfile.caddy-2.8.0-beta.2 --push .

  build_and_push_v2-10-0:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'build/caddy:2.10.0') || contains(github.event.head_commit.message, 'build/all')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      run: cd ./caddy && docker buildx build --tag rlkvch/caddy:2.10.0 --tag rlkvch/caddy:v2.10-latest --tag biggiko/caddy:v2.10 --tag biggiko/caddy:v2.10-latest --platform linux/amd64,linux/arm64 -f Dockerfile.caddy-2.10.0 --push .
